### PR TITLE
505: Ensure custom delete handling deletes a whole line when one vertex selected

### LINKED ISSUE #505: Errors with selecting/deleting points
- [x] The app crashes if you have one point of a line selected and click trash. ` Uncaught Error: a line needs to have two or more coordinates to be valid`

- [x] After drawing a new polygon, if it's still unlabeled, you cannot select a single point without dragging that point. 

- [x] Upon deleting an unlabeled polygon, the label form persists with red outline. It should go away.

- [x] If you try to deselect an unlabeled polygon the form turns red/invalid, then add a label to make it valid, then deselect it, then reselect it, the form is again red/invalid. So selecting a polygon that was ever invalid defaults to having an invalid form, even if the label field is filled out.

### PR DESCRIPTION
**Pull request by julialucyhogan**
related to issue #505, but does not close it as other bugs were added to that ticket and are addressed in a different PR.

### CODE REVIEW

File: app/components/project-geometries/modes/draw.js [hunk 1]
```diff
@@ -155,24 +155,26 @@ export default class DrawComponent extends Component {
...
   @action
   handleTrashButtonClick() {
     const { draw: { drawInstance: draw } } = this.get('map');
     const { features: [selectedFeaturePoint] } = draw.getSelectedPoints();
     const { features: [selectedFeature] } = draw.getSelected();
 
-    // if user attempts to delete a vertex that renders the polygon invalid (i.e. < 4 vertices)
-    // then select the entire polygon Feature for deletion in simple_select_delete mode
+    // if user attempts to delete a vertex from a line
+    // or attempts to delete a vertex that renders a polygon invalid (i.e. < 4 vertices)
```
Comment (andycochran) [inline app/components/project-geometries/modes/draw.js]: An invalid polygon is < 3 vertices, no?

Comment (julialucyhogan) [reply app/components/project-geometries/modes/draw.js]: visually to a human yes. But the start/end vertex exists 2x in the Polygon of mapbox world. So if a shape has < 5 points (aka 4, the threshold for validity), then we must delete the whole when deleting a single vertex.
