### PR TITLE
275: Visually deselect single lot

### LINKED ISSUE #275: User should be able to deselect/select a single lot
In lot mode, you can’t deselect a lot when it’s the only lot selected. If you click the selected lot, it stays highlighted. However, I assume that (even though it’s highlighted) it’s not actually part of the selection, because when you click another lot the previously selected lot is deselected. So, if you click a single selected lot multiple times, you don’t know if it’s selected or not until you click some other lot. Then, whether or not it stays selected depends on if you’ve clicked it an even or odd number of times. 

This bug will be frustrating in this use case:
- User has a project that’s one lot
- They select the wrong one
- They try to deselect it before selecting the right one
- They click it a number of times, becoming frustrated that the wrong lot is still selected

### PR DESCRIPTION
**Pull request by julialucyhogan**
closes #275

### CODE REVIEW

File: app/components/project-geometries/modes/lots.js [hunk 1]
```diff
@@ -145,6 +151,7 @@ export default class LotsComponent extends Component {
         .features
         .filter(lot => lot.properties.bbl !== properties.bbl);
 
+      console.log('NEW LOTS', newLots);
```
Comment (andycochran) [inline app/components/project-geometries/modes/lots.js]: Remove log.

File: app/components/project-geometries/modes/lots.js [hunk 2]
```diff
@@ -84,11 +84,17 @@ export default class LotsComponent extends Component {
...
+        type: 'FeatureCollection',
+        features: [],
+      });
+      return;
+    }
     const [{ geometry }] = features;
     const { length } = features;
 
-    return waitForProperty(this, 'hydrateFeatures.isIdle')
+    waitForProperty(this, 'hydrateFeatures.isIdle')
```
Comment (allthesignals) [inline app/components/project-geometries/modes/lots.js]: This can definitely happen in parallel with other things but we should keep in mind that `waitForProperty` is async and we might need to await it somewhere

Comment (julialucyhogan) [reply app/components/project-geometries/modes/lots.js]: does `return` give you `await` behavior?
